apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base    # 引用基础配置

namePrefix: prod-  # 给所有资源添加 prod- 前缀

# 生产环境特定的资源配置
resources: []

# 生产环境的补丁
patchesStrategicMerge:
  - deployment-patch.yaml

# 生产环境特定的配置
configMapGenerator:
  - name: e2e-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info